package ke.co.greid.entities;

// Generated Apr 1, 2015 12:52:51 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name = "address", catalog = "hims")
public class Address implements java.io.Serializable {

	private Integer addressId;
	private Patient patient;
	private String physicalResidence;
	private String cellPhone;
	private String homePhone;
	private String emailAddress;
	private String postBox;
	private String zipCode;
	private String city;

	public Address() {
	}

	public Address(Patient patient) {
		this.patient = patient;
	}

	public Address(Patient patient, String physicalResidence, String cellPhone,
			String homePhone, String emailAddress, String postBox,
			String zipCode, String city) {
		this.patient = patient;
		this.physicalResidence = physicalResidence;
		this.cellPhone = cellPhone;
		this.homePhone = homePhone;
		this.emailAddress = emailAddress;
		this.postBox = postBox;
		this.zipCode = zipCode;
		this.city = city;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "address_id", unique = true, nullable = false)
	public Integer getAddressId() {
		return this.addressId;
	}

	public void setAddressId(Integer addressId) {
		this.addressId = addressId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "patient_id", nullable = false)
	public Patient getPatient() {
		return this.patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

	@Column(name = "physical_residence", length = 45)
	public String getPhysicalResidence() {
		return this.physicalResidence;
	}

	public void setPhysicalResidence(String physicalResidence) {
		this.physicalResidence = physicalResidence;
	}

	@Column(name = "cell_phone", length = 45)
	public String getCellPhone() {
		return this.cellPhone;
	}

	public void setCellPhone(String cellPhone) {
		this.cellPhone = cellPhone;
	}

	@Column(name = "home_phone", length = 45)
	public String getHomePhone() {
		return this.homePhone;
	}

	public void setHomePhone(String homePhone) {
		this.homePhone = homePhone;
	}

	@Column(name = "email_address", length = 45)
	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	@Column(name = "post_box", length = 45)
	public String getPostBox() {
		return this.postBox;
	}

	public void setPostBox(String postBox) {
		this.postBox = postBox;
	}

	@Column(name = "zip_code", length = 45)
	public String getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	@Column(name = "city", length = 45)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

}
