package ke.co.greid.entities;

// Generated Apr 1, 2015 12:52:51 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BloodGroup generated by hbm2java
 */
@Entity
@Table(name = "blood_group", catalog = "hims")
public class BloodGroup implements java.io.Serializable {

	private Integer bloodGroupId;
	private String bloodGroupName;
	private String bloodGroupDesc;
	private String rhesus;
	private Set<Patient> patients = new HashSet<Patient>(0);

	public BloodGroup() {
	}

	public BloodGroup(String bloodGroupName, String bloodGroupDesc,
			String rhesus, Set<Patient> patients) {
		this.bloodGroupName = bloodGroupName;
		this.bloodGroupDesc = bloodGroupDesc;
		this.rhesus = rhesus;
		this.patients = patients;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "blood_group_id", unique = true, nullable = false)
	public Integer getBloodGroupId() {
		return this.bloodGroupId;
	}

	public void setBloodGroupId(Integer bloodGroupId) {
		this.bloodGroupId = bloodGroupId;
	}

	@Column(name = "blood_group_name", length = 45)
	public String getBloodGroupName() {
		return this.bloodGroupName;
	}

	public void setBloodGroupName(String bloodGroupName) {
		this.bloodGroupName = bloodGroupName;
	}

	@Column(name = "blood_group_desc", length = 45)
	public String getBloodGroupDesc() {
		return this.bloodGroupDesc;
	}

	public void setBloodGroupDesc(String bloodGroupDesc) {
		this.bloodGroupDesc = bloodGroupDesc;
	}

	@Column(name = "rhesus", length = 45)
	public String getRhesus() {
		return this.rhesus;
	}

	public void setRhesus(String rhesus) {
		this.rhesus = rhesus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bloodGroup")
	public Set<Patient> getPatients() {
		return this.patients;
	}

	public void setPatients(Set<Patient> patients) {
		this.patients = patients;
	}

}
