package ke.co.greid.entities;

// Generated Apr 1, 2015 12:52:51 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Chapter generated by hbm2java
 */
@Entity
@Table(name = "chapter", catalog = "hims")
public class Chapter implements java.io.Serializable {

	private String chapterNumber;
	private String chapterTitle;
	private Set<IcdCodes> icdCodeses = new HashSet<IcdCodes>(0);

	public Chapter() {
	}

	public Chapter(String chapterNumber) {
		this.chapterNumber = chapterNumber;
	}

	public Chapter(String chapterNumber, String chapterTitle,
			Set<IcdCodes> icdCodeses) {
		this.chapterNumber = chapterNumber;
		this.chapterTitle = chapterTitle;
		this.icdCodeses = icdCodeses;
	}

	@Id
	@Column(name = "chapter_number", unique = true, nullable = false, length = 2)
	public String getChapterNumber() {
		return this.chapterNumber;
	}

	public void setChapterNumber(String chapterNumber) {
		this.chapterNumber = chapterNumber;
	}

	@Column(name = "chapter_title", length = 110)
	public String getChapterTitle() {
		return this.chapterTitle;
	}

	public void setChapterTitle(String chapterTitle) {
		this.chapterTitle = chapterTitle;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chapter")
	public Set<IcdCodes> getIcdCodeses() {
		return this.icdCodeses;
	}

	public void setIcdCodeses(Set<IcdCodes> icdCodeses) {
		this.icdCodeses = icdCodeses;
	}

}
