package ke.co.greid.entities;

// Generated Apr 1, 2015 12:52:51 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CreditCard generated by hbm2java
 */
@Entity
@Table(name = "credit_card", catalog = "hims")
public class CreditCard implements java.io.Serializable {

	private int creditCardId;
	private Patient patient;
	private String cardNumber;
	private String issuer;
	private Date expiryDate;
	private String vcc;

	public CreditCard() {
	}

	public CreditCard(int creditCardId, Patient patient) {
		this.creditCardId = creditCardId;
		this.patient = patient;
	}

	public CreditCard(int creditCardId, Patient patient, String cardNumber,
			String issuer, Date expiryDate, String vcc) {
		this.creditCardId = creditCardId;
		this.patient = patient;
		this.cardNumber = cardNumber;
		this.issuer = issuer;
		this.expiryDate = expiryDate;
		this.vcc = vcc;
	}

	@Id
	@Column(name = "credit_card_id", unique = true, nullable = false)
	public int getCreditCardId() {
		return this.creditCardId;
	}

	public void setCreditCardId(int creditCardId) {
		this.creditCardId = creditCardId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "owner_id", nullable = false)
	public Patient getPatient() {
		return this.patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

	@Column(name = "card_number", length = 45)
	public String getCardNumber() {
		return this.cardNumber;
	}

	public void setCardNumber(String cardNumber) {
		this.cardNumber = cardNumber;
	}

	@Column(name = "issuer", length = 45)
	public String getIssuer() {
		return this.issuer;
	}

	public void setIssuer(String issuer) {
		this.issuer = issuer;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "expiry_date", length = 19)
	public Date getExpiryDate() {
		return this.expiryDate;
	}

	public void setExpiryDate(Date expiryDate) {
		this.expiryDate = expiryDate;
	}

	@Column(name = "vcc", length = 45)
	public String getVcc() {
		return this.vcc;
	}

	public void setVcc(String vcc) {
		this.vcc = vcc;
	}

}
