package ke.co.greid.entities;

// Generated Apr 1, 2015 12:52:51 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Gender generated by hbm2java
 */
@Entity
@Table(name = "gender", catalog = "hims")
public class Gender implements java.io.Serializable {

	private Integer genderId;
	private String genderName;
	private String genderDescription;
	private Set<Patient> patients = new HashSet<Patient>(0);

	public Gender() {
	}

	public Gender(String genderName, String genderDescription,
			Set<Patient> patients) {
		this.genderName = genderName;
		this.genderDescription = genderDescription;
		this.patients = patients;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "gender_id", unique = true, nullable = false)
	public Integer getGenderId() {
		return this.genderId;
	}

	public void setGenderId(Integer genderId) {
		this.genderId = genderId;
	}

	@Column(name = "gender_name", length = 45)
	public String getGenderName() {
		return this.genderName;
	}

	public void setGenderName(String genderName) {
		this.genderName = genderName;
	}

	@Column(name = "gender_description", length = 45)
	public String getGenderDescription() {
		return this.genderDescription;
	}

	public void setGenderDescription(String genderDescription) {
		this.genderDescription = genderDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gender")
	public Set<Patient> getPatients() {
		return this.patients;
	}

	public void setPatients(Set<Patient> patients) {
		this.patients = patients;
	}

}
