package ke.co.greid.entities;

// Generated Apr 1, 2015 12:52:51 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MaritalStatus generated by hbm2java
 */
@Entity
@Table(name = "marital_status", catalog = "hims")
public class MaritalStatus implements java.io.Serializable {

	private Integer maritalStatusId;
	private String maritalStatusName;
	private String maritalStatusDescription;
	private Set<Patient> patients = new HashSet<Patient>(0);

	public MaritalStatus() {
	}

	public MaritalStatus(String maritalStatusName,
			String maritalStatusDescription, Set<Patient> patients) {
		this.maritalStatusName = maritalStatusName;
		this.maritalStatusDescription = maritalStatusDescription;
		this.patients = patients;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "marital_status_id", unique = true, nullable = false)
	public Integer getMaritalStatusId() {
		return this.maritalStatusId;
	}

	public void setMaritalStatusId(Integer maritalStatusId) {
		this.maritalStatusId = maritalStatusId;
	}

	@Column(name = "marital_status_name", length = 45)
	public String getMaritalStatusName() {
		return this.maritalStatusName;
	}

	public void setMaritalStatusName(String maritalStatusName) {
		this.maritalStatusName = maritalStatusName;
	}

	@Column(name = "marital_status_description", length = 45)
	public String getMaritalStatusDescription() {
		return this.maritalStatusDescription;
	}

	public void setMaritalStatusDescription(String maritalStatusDescription) {
		this.maritalStatusDescription = maritalStatusDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "maritalStatus")
	public Set<Patient> getPatients() {
		return this.patients;
	}

	public void setPatients(Set<Patient> patients) {
		this.patients = patients;
	}

}
