package ke.co.greid.entities;

// Generated Apr 1, 2015 12:52:51 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * NextOfKin generated by hbm2java
 */
@Entity
@Table(name = "next_of_kin", catalog = "hims")
public class NextOfKin implements java.io.Serializable {

	private Integer nextOfKinId;
	private Relationship relationship;
	private Patient patient;
	private String surname;
	private String otherNames;

	public NextOfKin() {
	}

	public NextOfKin(Relationship relationship, Patient patient) {
		this.relationship = relationship;
		this.patient = patient;
	}

	public NextOfKin(Relationship relationship, Patient patient,
			String surname, String otherNames) {
		this.relationship = relationship;
		this.patient = patient;
		this.surname = surname;
		this.otherNames = otherNames;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "next_of_kin_id", unique = true, nullable = false)
	public Integer getNextOfKinId() {
		return this.nextOfKinId;
	}

	public void setNextOfKinId(Integer nextOfKinId) {
		this.nextOfKinId = nextOfKinId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "relationship_id", nullable = false)
	public Relationship getRelationship() {
		return this.relationship;
	}

	public void setRelationship(Relationship relationship) {
		this.relationship = relationship;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "patient_id", nullable = false)
	public Patient getPatient() {
		return this.patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

	@Column(name = "surname", length = 45)
	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	@Column(name = "other_names", length = 45)
	public String getOtherNames() {
		return this.otherNames;
	}

	public void setOtherNames(String otherNames) {
		this.otherNames = otherNames;
	}

}
