package ke.co.greid.entities;

// Generated Apr 1, 2015 12:52:51 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PatientHasMedicalInsuranceId generated by hbm2java
 */
@Embeddable
public class PatientHasMedicalInsuranceId implements java.io.Serializable {

	private int patientId;
	private int insuranceId;

	public PatientHasMedicalInsuranceId() {
	}

	public PatientHasMedicalInsuranceId(int patientId, int insuranceId) {
		this.patientId = patientId;
		this.insuranceId = insuranceId;
	}

	@Column(name = "patient_id", nullable = false)
	public int getPatientId() {
		return this.patientId;
	}

	public void setPatientId(int patientId) {
		this.patientId = patientId;
	}

	@Column(name = "insurance_id", nullable = false)
	public int getInsuranceId() {
		return this.insuranceId;
	}

	public void setInsuranceId(int insuranceId) {
		this.insuranceId = insuranceId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PatientHasMedicalInsuranceId))
			return false;
		PatientHasMedicalInsuranceId castOther = (PatientHasMedicalInsuranceId) other;

		return (this.getPatientId() == castOther.getPatientId())
				&& (this.getInsuranceId() == castOther.getInsuranceId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPatientId();
		result = 37 * result + this.getInsuranceId();
		return result;
	}

}
