package ke.co.greid.entities;

// Generated Apr 1, 2015 12:52:51 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PatientHasMedicalInsurance generated by hbm2java
 */
@Entity
@Table(name = "patient_has_medical_insurance", catalog = "hims")
public class PatientHasMedicalInsurance implements java.io.Serializable {

	private PatientHasMedicalInsuranceId id;
	private Patient patient;
	private MedicalInsurance medicalInsurance;
	private Date expiryDate;
	private String memberNumber;
	private BigDecimal balance;
	private String cardSerial;

	public PatientHasMedicalInsurance() {
	}

	public PatientHasMedicalInsurance(PatientHasMedicalInsuranceId id,
			Patient patient, MedicalInsurance medicalInsurance) {
		this.id = id;
		this.patient = patient;
		this.medicalInsurance = medicalInsurance;
	}

	public PatientHasMedicalInsurance(PatientHasMedicalInsuranceId id,
			Patient patient, MedicalInsurance medicalInsurance,
			Date expiryDate, String memberNumber, BigDecimal balance,
			String cardSerial) {
		this.id = id;
		this.patient = patient;
		this.medicalInsurance = medicalInsurance;
		this.expiryDate = expiryDate;
		this.memberNumber = memberNumber;
		this.balance = balance;
		this.cardSerial = cardSerial;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "patientId", column = @Column(name = "patient_id", nullable = false)),
			@AttributeOverride(name = "insuranceId", column = @Column(name = "insurance_id", nullable = false)) })
	public PatientHasMedicalInsuranceId getId() {
		return this.id;
	}

	public void setId(PatientHasMedicalInsuranceId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "patient_id", nullable = false, insertable = false, updatable = false)
	public Patient getPatient() {
		return this.patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "insurance_id", nullable = false, insertable = false, updatable = false)
	public MedicalInsurance getMedicalInsurance() {
		return this.medicalInsurance;
	}

	public void setMedicalInsurance(MedicalInsurance medicalInsurance) {
		this.medicalInsurance = medicalInsurance;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "expiry_date", length = 19)
	public Date getExpiryDate() {
		return this.expiryDate;
	}

	public void setExpiryDate(Date expiryDate) {
		this.expiryDate = expiryDate;
	}

	@Column(name = "member_number", length = 45)
	public String getMemberNumber() {
		return this.memberNumber;
	}

	public void setMemberNumber(String memberNumber) {
		this.memberNumber = memberNumber;
	}

	@Column(name = "balance", precision = 9)
	public BigDecimal getBalance() {
		return this.balance;
	}

	public void setBalance(BigDecimal balance) {
		this.balance = balance;
	}

	@Column(name = "card_serial", length = 45)
	public String getCardSerial() {
		return this.cardSerial;
	}

	public void setCardSerial(String cardSerial) {
		this.cardSerial = cardSerial;
	}

}
