package ke.co.greid.entities;

// Generated Apr 1, 2015 12:52:51 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Religion generated by hbm2java
 */
@Entity
@Table(name = "religion", catalog = "hims")
public class Religion implements java.io.Serializable {

	private Integer religionId;
	private String religionName;
	private Set<Patient> patients = new HashSet<Patient>(0);

	public Religion() {
	}

	public Religion(String religionName, Set<Patient> patients) {
		this.religionName = religionName;
		this.patients = patients;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "religion_id", unique = true, nullable = false)
	public Integer getReligionId() {
		return this.religionId;
	}

	public void setReligionId(Integer religionId) {
		this.religionId = religionId;
	}

	@Column(name = "religion_name", length = 45)
	public String getReligionName() {
		return this.religionName;
	}

	public void setReligionName(String religionName) {
		this.religionName = religionName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "religion")
	public Set<Patient> getPatients() {
		return this.patients;
	}

	public void setPatients(Set<Patient> patients) {
		this.patients = patients;
	}

}
